### ISSUE TITLE
error in execute python test.py

### ISSUE THREAD

**Issue by SalvoPisciotta** [yuPeiyu98/DRC#4]
TypeError: load() missing 1 required positional argument: 'Loader' occurs when I try to execute the provided command for testing

**Comment by yuPeiyu98** [comment]
Hi, sorry for the late reply. It seems that this is a pyyaml package incompatibility issue. Please refer to this link for possible solutions: https://stackoverflow.com/questions/69564817/typeerror-load-missing-1-required-positional-argument-loader-in-google-col.

Hope this helps.
